# Generated by Django 4.2 on 2023-05-31 07:43

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dat', models.DateField(verbose_name='Дата события')),
                ('title', models.TextField(max_length=255, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Описание')),
                ('slug', models.SlugField(null=True, verbose_name='Хранение изображения')),
                ('image', models.ImageField(null=True, upload_to='exh')),
            ],
            options={
                'verbose_name': 'Календарь',
                'verbose_name_plural': 'Календари',
            },
        ),
        migrations.CreateModel(
            name='Exhibition_tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Текст')),
                ('data_exhib', models.TextField(verbose_name='Дата проведения выставки')),
                ('slug', models.SlugField(null=True, verbose_name='Хранение изображения')),
                ('image', models.ImageField(null=True, upload_to='exh')),
            ],
            options={
                'verbose_name': 'Тематическая выставка',
                'verbose_name_plural': 'Тематические выставки',
            },
        ),
        migrations.CreateModel(
            name='Kontakt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='ФИО')),
                ('dol', models.CharField(max_length=255, verbose_name='Должность')),
                ('phoneNumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('secondPhoneNumber', models.TextField(max_length=4, verbose_name='Bнутренний')),
                ('mail', models.CharField(blank=True, max_length=255, verbose_name='Электронная почта')),
            ],
            options={
                'verbose_name': 'Работник',
                'verbose_name_plural': 'Работники',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Текст')),
                ('slug', models.SlugField(verbose_name='Хранение изображения')),
                ('image', models.ImageField(upload_to='nws')),
            ],
            options={
                'verbose_name': 'Новости',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Poln_text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('silka', models.CharField(max_length=20000, verbose_name='Ссылка на сайт')),
                ('text', models.TextField(verbose_name='Текст')),
                ('studtxt', models.TextField(blank=True, verbose_name='Для студента')),
                ('preptxt', models.TextField(blank=True, verbose_name='Для преподавателя')),
                ('vsetxt', models.TextField(blank=True, verbose_name='Общая')),
                ('slug', models.SlugField(null=True, verbose_name='Хранение изображения')),
                ('image', models.ImageField(null=True, upload_to='text')),
                ('stud', models.FileField(blank=True, upload_to='books/', verbose_name='Для студента')),
                ('prep', models.FileField(blank=True, upload_to='books/', verbose_name='Для преподавателя')),
                ('vse', models.FileField(blank=True, upload_to='books/', verbose_name='Общая')),
            ],
            options={
                'verbose_name': 'Полнотекстовый ресурс',
                'verbose_name_plural': 'Полнотекстовые ресурсы',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Новинки')),
            ],
            options={
                'verbose_name': 'Новинкa',
                'verbose_name_plural': 'Новинки',
            },
        ),
        migrations.CreateModel(
            name='Exh_nov_izpo_kom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=255, verbose_name='Краткое описание')),
                ('text', models.TextField(verbose_name='Текст')),
                ('slug', models.SlugField(null=True, verbose_name='Хранение изображения')),
                ('image', models.ImageField(null=True, upload_to='exh')),
                ('category', models.ManyToManyField(to='PRAKTIKA.tags', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Новинка издательско-полиграфического комплекса',
                'verbose_name_plural': 'Новинки издательско-полиграфического комплекса',
            },
        ),
        migrations.CreateModel(
            name='Exh_nov_iz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=255, verbose_name='Краткое описание')),
                ('text', models.TextField(verbose_name='Текст')),
                ('slug', models.SlugField(null=True, verbose_name='Хранение изображения')),
                ('image', models.ImageField(null=True, upload_to='exh')),
                ('category', models.ManyToManyField(to='PRAKTIKA.tags', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Новинка издательства',
                'verbose_name_plural': 'Новинки издательств',
            },
        ),
    ]
