# Generated by Django 4.2 on 2023-06-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRAKTIKA', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kontakt',
            name='mesto',
            field=models.CharField(blank=True, max_length=255, verbose_name='Место работы'),
        ),
    ]
