# Generated by Django 4.2 on 2023-06-09 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PRAKTIKA', '0002_kontakt_mesto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exh_nov_izpo_kom',
        ),
    ]
